### ISSUE TITLE
CMake tries to install non-existent `cmtp-responder.conf`

### ISSUE THREAD

**Issue by 1ace** [cmtp-responder/cmtp-responder#3]
The current [`CMakeLists.txt`](https://github.com/cmtp-responder/cmtp-responder/blob/3218119b9be45ce95309dec2b9d0c6cc074a60e3/CMakeLists.txt#L34) tries to install `cmtp-responder.conf`, but that file doesn't exist.

Maybe it was forgotten to be committed to the repository?

**Comment by andrzejtp** [comment]
True.

Fixed with https://github.com/cmtp-responder/cmtp-responder/commit/820796906c602cd288a99409b1fb5ef1b7d48944
