### ISSUE TITLE
Coverity analysis

### ISSUE THREAD

**Issue by 1ace** [cmtp-responder/cmtp-responder#6]
I have set up a Coverity analysis for this project with a first scan to see what can be fixed (note that I mistakenly sent a build on top of #5 instead of `master`):
https://scan.coverity.com/projects/cmtp-responder

I have sent you @andrzejtp an invitation to your collabora email address with the "owner" role, so it should transfer ownership to you as soon as you accept it :)

**Comment by andrzejtp** [comment]
Thanks, accepted.
